# 01 Data Quality Check

This notebook handles:
- Data loading
- Data type validation and conversion
- Missing value detection
- Data export for downstream analysis

## Setup and Data Loading

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('../../Data/raws/WA_Fn-UseC_-Telco-Customer-Churn.csv')

## Basic Data Overview

In [3]:
print("Dataset shape:", df.shape)
print("\nColumn data types:")
print(df.dtypes)
print("\nFirst few rows:")
df.head()

Dataset shape: (7043, 21)

Column data types:
customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

First few rows:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## Data Type Correction

TotalCharges should be numeric but may contain spaces or invalid values.

In [4]:
print("Data Type of TotalCharges:  ", df["TotalCharges"].dtype)
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

print(df["TotalCharges"].unique())

print("\n")

print("Min TotalCharges:", df["TotalCharges"].min())
print("Max TotalCharges:", df["TotalCharges"].max())

print("\n")

print("Skewness of TotalCharges:", df["TotalCharges"].skew())

Data Type of TotalCharges:   str
[  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]


Min TotalCharges: 18.8
Max TotalCharges: 8684.8


Skewness of TotalCharges: 0.961642499724251

In [9]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7032.000000
mean        0.162147    32.371149       64.761692   2283.300441
std         0.368612    24.559481       30.090047   2266.771362
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [12]:
print("Null values in each column:\n", df.isnull().sum())

Null values in each column:
 customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
ChargeGroup          0
dtype: int64

In [13]:
print("Duplicate rows in the dataset:", df.duplicated().sum())

Duplicate rows in the dataset: 0

- ข้อมูลมีความเอียงเล็กน้อย ยังพอไช้ได้

In [5]:
print("Missing values per column:")
print(df.isnull().sum())
print("\nTotal missing values:", df.isnull().sum().sum())

Missing values per column:
customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

Total missing values: 11

In [15]:
df.select_dtypes(include=['int64', 'float64']).skew()

SeniorCitizen     1.833633
tenure            0.239540
MonthlyCharges   -0.220524
TotalCharges      0.961642
dtype: float64

- ข้อมูล Senior Citizen มีความเอียงข้อมูลมาก ต้องปรับวิธีวัด

In [20]:
#Validate Categorical Columns
df.nunique()

print("Unique values in each categorical column:")
for col in df.columns:
    print(col)
    print(df[col].unique())
    print("-----------------=------------------")

Unique values in each categorical column:
customerID
<StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7043, dtype: str
-----------------=------------------
gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
-----------------=------------------
SeniorCitizen
[0 1]
-----------------=------------------
Partner
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
-----------------=------------------
Dependents
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------=------------------
tenure
[ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]
-----------------=------------------
PhoneService
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------=------------------
MultipleLines
<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
-----------------=------------------
InternetService
<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
-----------------=------------------
OnlineSecurity
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
-----------------=------------------
OnlineBackup
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
-----------------=------------------
DeviceProtection
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
-----------------=------------------
TechSupport
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
-----------------=------------------
StreamingTV
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
-----------------=------------------
StreamingMovies
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
-----------------=------------------
Contract
<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
-----------------=------------------
PaperlessBilling
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
-----------------=------------------
PaymentMethod
<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
-----------------=------------------
MonthlyCharges
[29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
-----------------=------------------
TotalCharges
[  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
-----------------=------------------
Churn
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------=------------------
ChargeGroup
[(18.249, 35.5], (35.5, 70.35], (70.35, 89.85], (89.85, 118.75]]
Categories (4, interval[float64, right]): [(18.249, 35.5] < (35.5, 70.35] < (70.35, 89.85] < (89.85, 118.75]]
-----------------=------------------

In [7]:
df["ChargeGroup"] = pd.qcut(df["MonthlyCharges"], 4)

In [8]:
# Save cleaned data for next step
df.to_csv('../../data/clean/cleaned_telco_churn.csv', index=False)
print("✓ Cleaned data saved to: data/clean/cleaned_telco_churn.csv")

✓ Cleaned data saved to: data/clean/cleaned_telco_churn.csv

---

**Next:** [02_business_rules.ipynb](02_business_rules.ipynb) — Business logic validation